"""
╔══════════════════════════════════════════════════════════════════════════════╗
║                    PRIMAX AI - NVIDIA NIM Client                              ║
║                                                                               ║
║  Copyright (c) 2024-2025 Bakery Street Project - ALL RIGHTS RESERVED         ║
║  WATERMARK: PRIMAX-AI-NIM-BSP-2025                                            ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""

import os
import asyncio
from typing import Optional, Dict, Any
from dataclasses import dataclass

@dataclass
class CodeGenerationResult:
    code: str
    language: str
    explanation: str
    model: str

class NimClient:
    """NVIDIA NIM API client for free LLM inference"""
    
    BASE_URL = "https://integrate.api.nvidia.com/v1"
    
    def __init__(self, api_key: Optional[str] = None):
        self.api_key = api_key or os.getenv("NIM_API_KEY") or os.getenv("NVIDIA_API_KEY")
        self.available = self.api_key is not None
        self._client = None
    
    async def _get_client(self):
        if self._client is None:
            try:
                import httpx
                self._client = httpx.AsyncClient(
                    base_url=self.BASE_URL,
                    headers={"Authorization": f"Bearer {self.api_key}"}
                )
            except ImportError:
                self.available = False
        return self._client
    
    async def generate_code(
        self,
        prompt: str,
        language: str = "python",
        context: Optional[str] = None
    ) -> CodeGenerationResult:
        if not self.available:
            raise RuntimeError("NIM API key not available - set NIM_API_KEY environment variable")
        
        client = await self._get_client()
        
        system_prompt = f"You are a helpful coding assistant. Generate {language} code."
        if context:
            full_prompt = f"{system_prompt}\n\nContext: {context}\n\nTask: {prompt}"
        else:
            full_prompt = f"{system_prompt}\n\nTask: {prompt}"
        
        try:
            response = await client.post(
                "/chat/completions",
                json={
                    "model": "meta/llama-3.1-8b-instruct",
                    "messages": [
                        {"role": "system", "content": system_prompt},
                        {"role": "user", "content": full_prompt}
                    ],
                    "max_tokens": 2048,
                    "temperature": 0.7
                }
            )
            
            data = response.json()
            code = data["choices"][0]["message"]["content"]
            
            return CodeGenerationResult(
                code=code,
                language=language,
                explanation="Generated by NVIDIA NIM (free tier)",
                model="meta/llama-3.1-8b-instruct"
            )
        except Exception as e:
            raise RuntimeError(f"NIM API error: {str(e)}")
    
    async def analyze_code(self, code: str, language: str = "python") -> Dict[str, Any]:
        if not self.available:
            raise RuntimeError("NIM API key not available")
        
        client = await self._get_client()
        
        prompt = f"""Analyze this {language} code for quality, bugs, and improvements:

{code}

Provide:
1. Issues found
2. Suggestions for improvement
3. Security considerations
"""
        
        try:
            response = await client.post(
                "/chat/completions",
                json={
                    "model": "meta/llama-3.1-8b-instruct",
                    "messages": [{"role": "user", "content": prompt}],
                    "max_tokens": 1024,
                    "temperature": 0.5
                }
            )
            
            data = response.json()
            return {
                "analysis": data["choices"][0]["message"]["content"],
                "model": "meta/llama-3.1-8b-instruct"
            }
        except Exception as e:
            raise RuntimeError(f"NIM API error: {str(e)}")