"""
╔══════════════════════════════════════════════════════════════════════════════╗
║                    PRIMAX AI - Automated PR Workflows                          ║
║                                                                               ║
║  Copyright (c) 2024-2025 Bakery Street Project - ALL RIGHTS RESERVED         ║
║  WATERMARK: PRIMAX-AI-WORKFLOW-BSP-2025                                       ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""

import subprocess
from typing import List, Optional
from dataclasses import dataclass


@dataclass
class PRWorkflowConfig:
    repo: str
    branch: str
    title: str
    body: str
    labels: Optional[List[str]] = None
    assignees: Optional[List[str]] = None
    reviewers: Optional[List[str]] = None


class PRWorkflowManager:
    def __init__(self):
        self.configured = self._check_gh_cli()

    def _check_gh_cli(self) -> bool:
        try:
            result = subprocess.run(
                ["gh", "auth", "status"], capture_output=True, text=True, timeout=10
            )
            return result.returncode == 0
        except Exception:
            return False

    def create_pr(self, config: PRWorkflowConfig) -> Optional[str]:
        if not self.configured:
            return None

        cmd = [
            "gh",
            "pr",
            "create",
            "--base",
            config.branch,
            "--title",
            config.title,
            "--body",
            config.body,
        ]

        if config.labels:
            cmd.extend(["--label", ",".join(config.labels)])
        if config.assignees:
            cmd.extend(["--assignee", ",".join(config.assignees)])
        if config.reviewers:
            cmd.extend(["--reviewer", ",".join(config.reviewers)])

        try:
            result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
            if result.returncode == 0:
                return result.stdout.strip()
        except Exception:
            pass
        return None

    def auto_merge_pr(self, pr_url: str, merge_method: str = "squash") -> bool:
        if not self.configured:
            return False

        try:
            result = subprocess.run(
                ["gh", "pr", "merge", pr_url, "--method", merge_method, "--auto"],
                capture_output=True,
                text=True,
                timeout=30,
            )
            return result.returncode == 0
        except Exception:
            return False

    def create_release(
        self, repo: str, tag: str, name: str, notes: str = ""
    ) -> Optional[str]:
        if not self.configured:
            return None

        try:
            result = subprocess.run(
                ["gh", "release", "create", tag, "--title", name, "--notes", notes],
                capture_output=True,
                text=True,
                timeout=30,
            )
            if result.returncode == 0:
                return result.stdout.strip()
        except Exception:
            pass
        return None


def generate_pr_body(features: List[str], changes: List[str], testing: str = "") -> str:
    body = "## Summary\n"
    body += "This PR includes the following features:\n\n"
    for f in features:
        body += f"- {f}\n"

    body += "\n## Changes\n"
    for c in changes:
        body += f"- {c}\n"

    if testing:
        body += f"\n## Testing\n{testing}\n"

    body += "\n---\n*Generated by PRIMAX AI*"
    return body


if __name__ == "__main__":
    manager = PRWorkflowManager()

    if not manager.configured:
        print("GitHub CLI not configured")
        exit(1)

    config = PRWorkflowConfig(
        repo="kilisan/primax-ai",
        branch="main",
        title="PRIMAX AI Enhancement",
        body=generate_pr_body(
            ["Nexus agent integration", "AST codebase scanner"],
            ["Added src/nexus_adapter.py", "Added src/codebase_scanner.py"],
        ),
    )

    pr_url = manager.create_pr(config)
    if pr_url:
        print(f"Created PR: {pr_url}")
    else:
        print("Failed to create PR")
